spring:
  profiles:
    active: local

---
jwt:
  secret:cobook@$&

spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://54.180.126.17:3306/cobook
    username: cobook
    password: cobook
    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: cobookservice2020@gmail.com
    password: hqltrepxhfnlohfn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 722675530533-8lddsa5lo60rlmmlijrno06n5elge0tn.apps.googleusercontent.com
            client-secret: bFE2aTcKEFwHSDhrMyUrUJz2

custom:
  oauth2:
    kakao:
      client-id: 8160c09915d18b2d717f58f39f209d61
      client-secret: pW1lBMjL9wgNJYGnKeuMG1IjnrgpIFHu
---
#spring:
#  profiles: dev
#    include: cobook
