spring:
  profiles:
    active: local
server:
  port: 8090
#  ssl:
#    enabled: true
#    key-store: cobook.jks # 1번에서 생성한 Key store 경로와 파일명을 적어줍니다.
#    key-store-password: cobook  # 1번에서 생성한 Key store의 비밀번호를 적어줍니다.
#    key-password: cobook # 1번에서 생성한 키스토어의 마지막의 키 비밀번호
#    key-alias: cobook-ssl # 키 스토어 별칭
#    trust-store: cobook.ts # 2번에서 생성한 Trust-Store 경로
#    trust-store-password: cobook # Trust-Store 비밀번호
---
jwt:
  secret:cobook@$&

spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/cobook
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: $your_user_name
    password: $your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: $your_client_id
            client-secret: $your_client_pass

custom:
  oauth2:
    kakao:
      client-id: $your_client_id
      client-secret: $your_client_pass
---
#spring:
#  profiles: dev
#    include: cobook