spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/cobook
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret: 

custom:
  oauth2:
    kakao:
      client-id:
      client-secret:
---
#spring:
#  profiles: dev
#    include: cobook