spring:
  profiles:
    active: local

---
jwt:
  secret:cobook@$&

spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://54.180.126.17:3306/cobook
    username: cobook
    password: cobook
    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: cobookservice2020@gmail.com
    password: hqltrepxhfnlohfn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
---
#spring:
#  profiles: dev
#    include: cobook
